name: plasmid-screen
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3
  - biopython=1.74
  - checkm-genome=1.1.3
  - quast=5.0.2
  - trim-galore=0.6.5
  - unicycler=0.4.8
  - mob_suite=3.0.1
  - abricate=1.0.1

