on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
name: Tests
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - nextflow_version: "21.04.3"
            java_version: "8"
          - nextflow_version: "24.10.6"
            java_version: "17"
    name: Nextflow v${{ matrix.nextflow_version }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create Artifacts Directory
      run: mkdir artifacts
    - name: Set up Java 8 for old Nextflow
      if: matrix.nextflow_version == '21.04.3'
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java_version }}
    - name: Set up Java 17 for newer Nextflow
      if: matrix.nextflow_version == '24.10.6'
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java_version }}
    - name: Install Miniconda
      run: bash .github/scripts/install_conda.sh
    - name: Install Nextflow
      env:
        NXF_VER: ${{ matrix.nextflow_version }}
      run: bash .github/scripts/install_nextflow.sh
    - name: Create ART Read-Simulation Environment
      run: bash .github/scripts/create_art_environment.sh
    - name: Download Assemblies
      run: bash .github/scripts/download_assemblies.sh
    - name: Simulate Reads
      run: bash .github/scripts/simulate_reads.sh
    - name: Create Mash & BLAST Environment
      run: bash .github/scripts/create_mash_and_blast_environment.sh
    - name: Download mob-suite db
      run: bash .github/scripts/download_mob-suite_db.sh
    - name: Create SampleSheet
      run: bash .github/scripts/create_samplesheet.sh
    - name: Run Pipeline
      run: bash .github/scripts/run_pipeline.sh
    - name: Create Output Checking Environment
      run: bash .github/scripts/create_output_checking_environment.sh
    - name: Check Outputs
      run: bash .github/scripts/check_outputs.sh
    - name: Prepare Artifacts
      if: always()
      run: bash .github/scripts/prepare_artifacts.sh
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: artifacts-BCCDC-PHL-routine-assembly-nextflow-v${{ matrix.nextflow_version }}-${{ github.run_id }}.${{ github.run_attempt }}
        path: artifacts
